In [66]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

In [67]:
image1 = cv2.imread('/home/timothee.teyssier/Documents/home/Documents/5-IMI/Calibrage/mire_1.png')
image2 = cv2.imread('/home/timothee.teyssier/Documents/home/Documents/5-IMI/Calibrage/mire_2.png')
# cv2.imshow('image1', image1)
# cv2.waitKey(0)
# cv2.imshow('image2', image2)
# cv2.waitKey(0)
# cv2.destroyAllWindows() 

In [68]:
ret1, corners1 = cv2.findChessboardCorners(image1,(11,8))
ret2, corners2 = cv2.findChessboardCorners(image2,(11,8))   #number of points it has to find
# print(ret1)
print(len(corners1))
print(corners1)
# print(ret2)
print(len(corners2))

88
[[[569.15533  387.40332 ]]

 [[519.4816   385.9438  ]]

 [[470.1172   384.61594 ]]

 [[419.7884   383.28775 ]]

 [[369.6076   382.3157  ]]

 [[318.4884   381.37213 ]]

 [[267.53342  380.38293 ]]

 [[215.46744  379.35266 ]]

 [[162.99219  378.62924 ]]

 [[109.80231  378.0184  ]]

 [[ 54.955513 377.48337 ]]

 [[565.95764  336.73398 ]]

 [[517.60333  335.4439  ]]

 [[468.5475   333.93002 ]]

 [[419.5133   332.52423 ]]

 [[369.70242  331.18527 ]]

 [[319.72803  330.18427 ]]

 [[269.2293   328.9239  ]]

 [[218.49387  328.02762 ]]

 [[166.82867  326.98392 ]]

 [[114.38393  325.8484  ]]

 [[ 60.66472  325.21472 ]]

 [[563.5097   288.04315 ]]

 [[515.45215  286.43924 ]]

 [[467.4098   284.9126  ]]

 [[418.7464   283.35608 ]]

 [[370.15646  282.12717 ]]

 [[320.63373  280.69492 ]]

 [[271.1921   279.65094 ]]

 [[220.88191  278.4358  ]]

 [[170.5534   277.28763 ]]

 [[118.79167  275.6171  ]]

 [[ 66.35025  274.22665 ]]

 [[560.81433  240.57297 ]]

 [[513.6825   239.04773 ]]

 [[466.18497  237

In [69]:
# print(corners1.shape)
corners1_squeeze = np.squeeze(corners1, axis=1)
# print(corners2.shape)
corners2_squeeze = np.squeeze(corners2, axis=1)
# print(corners1.shape)

In [70]:
coord_px = np.concatenate((corners1_squeeze, corners2_squeeze), axis=0)
print(len(coord_px))

176


In [72]:
# min_x = []
origine_2D = corners1_squeeze[0]
print(origine_2D)

[569.15533 387.40332]


In [96]:
coord_mm = []
for k in range(8):
    for j in range(11):
        if len(coord_mm)<88:
            pos_mm_i = np.array([[j*(-20),k*20,0]])
            print(pos_mm_i)
            # print(coord_mm)
            coord_mm.append(pos_mm_i)
            print(coord_mm)
        # else:
        #     pos_mm_i = np.array([[j*(-20),k*20,100]])
        #     coord_mm = np.concatenate((coord_mm,pos_mm_i), axis=1)
print(coord_px.shape)
coord_mm = np.array(coord_mm)
print(coord_mm.shape)

[[0 0 0]]
[array([[0, 0, 0]])]
[[-20   0   0]]
[array([[0, 0, 0]]), array([[-20,   0,   0]])]
[[-40   0   0]]
[array([[0, 0, 0]]), array([[-20,   0,   0]]), array([[-40,   0,   0]])]
[[-60   0   0]]
[array([[0, 0, 0]]), array([[-20,   0,   0]]), array([[-40,   0,   0]]), array([[-60,   0,   0]])]
[[-80   0   0]]
[array([[0, 0, 0]]), array([[-20,   0,   0]]), array([[-40,   0,   0]]), array([[-60,   0,   0]]), array([[-80,   0,   0]])]
[[-100    0    0]]
[array([[0, 0, 0]]), array([[-20,   0,   0]]), array([[-40,   0,   0]]), array([[-60,   0,   0]]), array([[-80,   0,   0]]), array([[-100,    0,    0]])]
[[-120    0    0]]
[array([[0, 0, 0]]), array([[-20,   0,   0]]), array([[-40,   0,   0]]), array([[-60,   0,   0]]), array([[-80,   0,   0]]), array([[-100,    0,    0]]), array([[-120,    0,    0]])]
[[-140    0    0]]
[array([[0, 0, 0]]), array([[-20,   0,   0]]), array([[-40,   0,   0]]), array([[-60,   0,   0]]), array([[-80,   0,   0]]), array([[-100,    0,    0]]), array([[-120,